
#
# Module Manifest for Module 'TeamsEdu.psd1
#
# This manifest file is a PowerShell hashtable with all technical requirements for this module
# This module was autogenerated by ISESteroids (http://www.isesteroids.com)
#
# Generated: 2020-05-01
# 

@{

# Module Loader File
RootModule = 'loader.psm1'

# Version Number
ModuleVersion = '0.9.5'

# Unique Module ID
GUID = '6d939bc7-10d8-4fba-9ffe-d24c88e892c1'

# Module Author
Author = 'Markus Hupfauer'

# Company
CompanyName = 'XITASO GmbH'

# Copyright
Copyright = '(c) 2020 XITASO GmbH. All rights reserved.'

# Module Description
Description = 'Migriert ASV Daten des Bundeslands Bayern zu Office 365.
Es wird für jede Klasse (z.B. 5a) und jedes Fach das Schüler dieser Klasse besuchen ein Team angelegt.
Die jeweilig zugeordnete Lehrkraft wird als Eigentümer des Teams gesichert.

Folgende Daten werden durch dieses Script an Microsoft übertragen:
- Vor- / Zunamen von Schülern & Lehrern
- Klassenzusammensetzungen & -bezeichnungen

Genauere Informationen können unter https://github.com/mhupfauer/TeamsEducation eingesehen werden.
'

# Required Modules (will load before this module loads)
RequiredModules = @('AzureAD','MicrosoftTeams', 'Microsoft.Graph')


# List of exportable functions
FunctionsToExport = @('Start-MigrationEnv', 'Start-ClassMigration', 'Start-StudentMigration', 'Start-TeacherMigration','Get-DataFromAsvXml', 'Close-LegacyTeams', 'Remove-LegacyUsers', 'Update-UserLicenses', 'New-BroadcastMessage')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Teams','Education','Deutschland','Bayern','ASV','Schulverwaltung','Gymnasium','Oberstufe','Realschule','Mittelschule','Corona','Homeschooling'

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/mhupfauer/TeamsEducation/master/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/mhupfauer/TeamsEducation'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '* 0.9.1 => Added functionality to retire teams from the previous school year.
* 0.9.2 => Added functionality to retire users from the previous school year.
           Stability improvements.
* 0.9.3 => Added ability to create senior classes and map users propperly
           Overall speed improvements by reducing complexity of user resolving
* 0.9.4 => Stability improvements. 
           0.9.4 has been fully tested on production ASV data for a bavarian gymnasium.
* 0.9.5 => Significantly imporved speed of class creation by batching user additions via Graph
           0.9.5 has been fully tested on production ASV data for multiple bavarian "Gymnasium".'

        # Prerelease string of this module
        Prerelease = '-RC'

        # Flag to indicate whether the module requires explicit user acceptance for install/update
        RequireLicenseAcceptance = $true

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable


}